.github/dependabot.yml
Configure Dependabot for the repository.
=> chore: Dependabot 

.eslintignore, .eslintrc.json, .eslintrc.ts.json, benchmark/mongoose.js, benchmark/papr.js, benchmark/run.js, benchmark/setup.js, example/find.ts, example/insert.ts, package.json, src/__tests__/index.test.ts, tests/cjs/index.js, tests/esm/index.js
Use [`eslint-plugin-import`](https://github.com/benmosher/eslint-plugin-import) for ordering imports.
=> test: Use eslint-plugin-import

docs/getting-started.md, example/README.md, example/papr.ts, example/transaction.ts
Add example code for using transactions.
Closes #12
=> docs: Transactions example

benchmark/setup.js, docs/README.md
Fixes #20 
Not sure why it's pulling commits through from my last branch when the they already merged. Let me know if that is an issue.
=> fix: Customize benchmark db name via CLI arg

docs/README.md, docs/getting-started.md
=> docs: Fix About and Getting Started code

src/utils.ts
=> fix: Fix insert and projection types

docs/api/model.md, src/__tests__/model.test.ts, src/model.ts
=> feat: Model.findOneAndDelete

docs/api/schema.md, src/__tests__/schema.test.ts, src/index.ts, src/model.ts, src/schema.ts, src/utils.ts
=> feat: Support IDs with strings or numbers

benchmark/setup.js, docs/README.md, docs/api/papr.md, docs/getting-started.md, example/papr.ts, src/index.ts, tests/cjs/index.js, tests/esm/index.js
=> docs: Import MongoClient from mongodb

docs/_sidebar.md, docs/api/model.md, docs/api/schema.md, docs/api/utils.md, docs/build.js, example/User.ts, src/model.ts, src/schema.ts, src/utils.ts
=> docs: Document ProjectionType util

docs/schema.md
Address a common issue in new folks to the library:
#130 
#80
=> docs: Document strictNullChecks requirement

docs/README.md, docs/api/model.md, src/model.ts
=> docs: Better docs for aggregate()

benchmark/mongoose.js, benchmark/papr.js, benchmark/run.js, docs/api/types.md, src/__tests__/schema.test.ts, src/__tests__/types.test.ts, src/types.ts
This adds a decimal 128 type along with tests for issue [94](https://github.com/plexinc/papr/issues/94)
=> feat: `decimal` type

CONTRIBUTING.md, README.md, package.json
To attract more open source contributors we should provide some basic guidelines of contributing to the repository.
=> docs: Add Contributing document

.github/workflows/ci.yaml
Makes the yarn cache keys simpler.
=> test: Update the yarn cache keys in CI

.eslintrc.json, .github/workflows/ci.yaml, .gitignore, build.sh, package.json, tests/build.sh, tests/cjs/package.json, tests/esm/package.json, tests/ts/index.ts, tests/ts/package.json, tests/ts/tsconfig.json
This is mostly inspired by the code from #460.
It occurred to me that we should have a sanity test for TypeScript after we built the NPM package.
=> test: Test built package with TypeScript

docs/recipes.md
I think it is useful to provide a list of available Papr integrations in readme file.
=> docs: Add list of available integrations

docs/recipes.md
Fix example to be consistent between Mongoose and Papr
=> docs: Fix recipies code consistency

.github/workflows/plex.yaml
This workflow will send a Slack message to the Plex Slack integration.
=> test: Notify Plex on PRs

.github/workflows/ci.yaml, package.json
Add node.js v22 in the build matrix test.
=> test: Test on node.js v22

docs/api/schema.md, docs/api/types.md, src/__tests__/model.test.ts, src/__tests__/schema.test.ts, src/__tests__/types.test.ts, src/schema.ts, src/types.ts
We want to improve the docs & tests around const enums, as we've run into these recently.
cc @jtassin since you added these initial docs & tests.
=> test: Improve docs & tests of const enums
