- src/__tests__/model.test.ts
- src/model.ts
I noticed this deprecation message in the logs:
```
collection.findOneAndUpdate option [returnOriginal] is deprecated and will be removed in a later version
```
When I looked up the [docs](https://mongodb.github.io/node-mongodb-native/3.6/api/Collection.html#findOneAndUpdate), I found:
* replace `returnOriginal` with `returnDocument`
> fix: Use returnDocument instead of returnOriginal

- benchmark/setup.js
- docs/README.md
- package.json
- yarn.lock
… their own mongodb instance url
Happy to remove the `arg` dependency if you don't want to add that, I can parse it manually.
> fix: Customize mongo URL in benchmark tool

- tests/build.sh
#26 has some errors in the build tests, but the bash script running those tests does not fail on errors, so CI shows those tests as :heavy_check_mark:.
> test: Fail early in build tests

- benchmark/mongoose.js
- benchmark/papr.js
- benchmark/run.js
- benchmark/setup.js
- docs/README.md
- package.json
- yarn.lock
While running benchmarks for #36, I noticed that the Mongoose benchmark was not correct because Mongoose adds a final `s` to the collection name. So the collection name we were using for Mongoose tests (`mongooses`) did not have the correct indexes defined.
However even after this change, the Mongoose numbers are still worse than Papr's.
I also bumped the `mongodb` library to the latest v3.6 version available.
> test: Update collections in benchmark

- src/__tests__/model.test.ts
- src/model.ts
We forgot to apply the default values in update+upsert operations in `bulkWrite`.
> fix: Apply defaults in bulkWrite updateOne operations

- example/README.md
- example/bulkWrite.ts
- src/__tests__/model.test.ts
- src/model.ts
- src/utils.ts
The fix in #41 did not account for fields that could be set in `$set`, `$inc`, `$unset` and `$push` - which can trigger conflicts errors.
> fix: Filter defaults in bulkWrite to avoid conflicts

- src/__tests__/model.test.ts
- src/model.ts
We were not supporting custom `createdAt` and `updatedAt` values in `insertOne` and `insertMany` operations.
> fix: Support custom dates in insert operations

- package.json
- yarn.lock
See https://github.com/mongodb/node-mongodb-native/releases/tag/v4.1.1
Several performance and TypeScript bugs were fixed in this version, so we recommend using it.
> fix: Require mongodb >=v4.1.1

- package.json
- tests/cjs/index.js
- tests/esm/index.js
- yarn.lock
The new `mongodb-memory-server` versions default to download the mongodb v5.0.3 server version, even when using the version specific packages e.g. `mongodb-memory-server-global-4.4`.
We should be testing with mongodb v5 anyway, since it's the latest version.
> test: Use mongodb-memory-server

- build.sh
- package.json
- tests/build.sh
Closes #121
This will update the ESM build and add file extensions to the imports, so that we don't need to use the `--experimental-specifier-resolution=node` flag.
> fix: ESM build with file extensions

- docs/api/schema.md
- src/schema.ts
Two small fixes:
- VALIDATION_ACTIONS and VALIDATION_LEVEL weren't being imported in the example
- VALIDATION_ACTIONS was written as VALIDATION_ACTION
> docs: Fix docs about validation enums

- docs/api/types.md
- src/__tests__/types.test.ts
- src/types.ts
In my case, I want to avoid the usage of enum, replaced by union type.
I found out that `papr` works natively fine in this case :)
I just added a test on it and a piece of documentation.
Thx a lot for your lib btw :) 
```ts
tt: types.enum(
[
'FOO' as const,
'BAR' as const,
],
{ required: true },
),
```
resolves as `'FOO' | 'BAR'`
> fix: Support enum type with array of const values

- package.json
- src/model.ts
- src/utils.ts
- yarn.lock
The following change in `mongodb` requires changes in the return types of
`find*` methods to include `WithId`:
- https://github.com/mongodb/node-mongodb-native/pull/3039
> feat: Use mongodb v4.2.1

- src/__tests__/model.test.ts
- src/__tests__/schema.test.ts
- src/schema.ts
When building a schema we're currently assigning `TDefaults` to `Partial<TProperties>` which is breaking the type safety for creating new documents provided by `DocumentForInsertWithoutDefaults`. This is because that type util (correctly) removes supplied default values for the model from the required properties when inserting a document, but because _all_ properties from `TProperties` are included in the type definition, it results in no keys remaining.
This wasn't caught in testing because rather than supplying our `Model<>` type with the default value returned when creating a schema, we're directly gathering the default type via `typeof DEFAULTS`. This commit also updates the tests to pull the type from the returned schema type signature.
> fix: Improve defaults type at schema declaration

- src/__tests__/schema.test.ts
- src/types.ts
Hello!
This PR allows to declare explicit optional types for schemas.
Currently if we try to do something like this:
```ts
const value = schema({
age: types.number({ required: false }),
});
// age: number
```
`age` will be still required even if  `required` is set as `false`. 
With this changes, schema returns the correct type when `{required: false}` is passed in the options object
```ts
const value = schema({
age: types.number({ required: false }),
});
// age: number | undefined
```
Let me know how it looks and if something needs to be modified ✌
> fix: Allow explicit optional types on schemas

- docs/api/model.md
- src/__tests__/model.test.ts
- src/model.ts
- src/utils.ts
This adds our own version of the bulk write type, which takes into account the defaults for the `insertOne` operation.
> feat: Better `bulkWrite` types for insert operations

- docs/api/papr.md
- jest.config.cjs
- src/__tests__/index.test.ts
- src/index.ts
- src/model.ts
Closes #212
This removes the undocumented `ExternalModel` type support in `model()`. Since it was undocumented and untested, there are little changes except the actual source code.
> refactor: Remove custom model type support

- docs/api/types.md
- src/__tests__/schema.test.ts
- src/types.ts
closes #227
The more I looked into this, the more I became convinced that:
1. Array elements should be non-optional by default, full stop.
2. The reason they are not is a side-effect of the way types are built by papr, not an expected outcome of the papr design
For point 1. --  an array member being "required" or not has _zero_ impact on the generated JSON Schema. And a collection with a JSON schema validator will not validate a document that has `null` or `undefined` array members. (Try it yourself!)
For point 2. --   `types` methods do double duty in `papr`: they output the generated JSON schema for the schema and, through type-casting, generate typescript types to use in code. 
Before this change, the `array` method's return value was `GetType<Item[], Options>` In order to generate the …
> feat: Make array members non-optional by default

- build.sh
Noticed this locally, and @duncanbeevers [flagged this](https://github.com/plexinc/papr/pull/195#issuecomment-1129994806) as well. The `sed` command does not work on macOS as written.
Stack Overflow gave me the fix here: https://stackoverflow.com/questions/19456518/error-when-using-sed-with-find-command-on-os-x-invalid-command-code
Hopefully this works on linux as well 😬
> fix: Update sed command for macOS

- renovate.json
Per https://github.com/renovatebot/renovate/issues/11547#issuecomment-1168714087 we shouldn't be setting this (and I'm 99% certain we copied this from an internal repo anyway, given our private repository credentials aren't in this repo).
> chore: Remove incorrect config from renovate

- src/__tests__/types.test.ts
- src/types.ts
The type we were using before for `objectGeneric` seems to present some issues when combined with the new nested properties support in `UpdateFilter` in `mongodb` v4.8.
There's no reason to be using `ObjectType` there with a plain object, when we can just express that type using `Record`.
> fix: Use Record for objectGeneric type

- docs/api/types.md
- src/__tests__/types.test.ts
- src/types.ts
This is an alternative to the `any` type - providing the same escape hatch but with data returned as `unknown` which forces consumers to use assertions before using the properties.
> feat: `unknown` type

- docs/api/types.md
- src/__tests__/types.test.ts
- src/types.ts
Creates a union type of multiple other types.
This is useful when combined with `objectGeneric`.
> feat: `oneOf` type

- src/__tests__/model.test.ts
- src/utils.ts
In the `DocumentForInsert` type we are checking if `Extract<keyof TSchema, 'createdAt'> extends 'createdAt'`. When our `TSchema` does not have `'createdAt'` as a property, the expression `Extract<keyof TSchema, 'createdAt'>` produces `never`. This results in `never extends 'createdAt'` being the ternary we're using and somewhat confusingly [`never` will always extends `'createdAt'`](https://www.typescriptlang.org/play?#code/C4TwDgpgBA6gFgQ2AQQLYEkoF4oDsIBuEATlBAB7AS4AmAzlAOR2QDGAlgGbusBqCAGwCuERlAD8eIagBGJKAC4odYMXa4A5gFgAULtYB7XCqhUVS+EjSYcARgDcuoA) because `never` is the bottom type and technically in all other types.
This means the current check will always evaluate to true, and even for schemas without timestamps enabled we are allowing users to pass timestamp fields when inserting a …
> fix: Correct TimestampSchema ternary in DocumentForInsert

- docs/api/types.md
- src/TupleItems.ts
- src/__tests__/TupleItems.test.ts
- src/__tests__/types.test.ts
- src/types.ts
Adds a tuple type with optional property support.
In order to have our return type match the [JSON Schema implementation of tuples](https://json-schema.org/understanding-json-schema/reference/array.html#tuple-validation) we're leveraging the `minItems` property, setting it to the position of the last required property defined in the tuple.
If there are properties preceding a required property in the tuple they are implicitly required as well, because the order of a tuple array is ensured and we cannot require a 3rd property while allowing optional 1st and 2nd properties.
The return type is tuple of all required properties in a union with each additional type including the next tuple property in order.
> feat: `tuple` type

- package.json
- src/utils.ts
- yarn.lock
This version reverts a bug introduced in `mongodb` v4.9.0.
> fix: Upgrade mongodb to v4.9.1

- docs/api/model.md
- src/__tests__/model.test.ts
- src/model.ts
- src/utils.ts
Rather than exclusively requiring all `_id` properties be an ObjectId, we can allow for users to define their own `_id` in their schema and have it reflected when using `model.findById`.
This also updates `ProjectionType` to facilitate non-ObjectId `_id` properties. The resulting type for models _with_ ObjectId `_id` properties is unchanged, so I don't consider this breaking.
Effectively, when constructing our `ProjectionType` we're picking properties defined in our projection from `TSchema` - this means excluding the `_id` property (unless explicitly set in the projection). However, we then use the `mongodb` supplied generic `WithId` to add the `_id` property back in, since it is always included in projected results.
This is where the issue lies - because the `WithId` generic uses the …
> feat: Allow user definition of `_id` property type

- docs/api/model.md
- docs/build.js
- src/__tests__/model.test.ts
- src/model.ts
There's a little bit of nuance to getting the most performance out of a
query when you only care checking if there exists a row matching a given
query. This helper tries its best to query the DB in the most performant
way, and returns a boolean result.
Performance Notes:
- The query used is a `findOne`. The query engine can then start scanning and stop
as soon as it matches a single document.
- Project out a single column from the filter criteria (or project `_id`
if there is no filter). In this way we return a minimum of data, while
potentially allowing this to be a "covered" query if there is an index
that includes all the keys in the filter.
> feat: Add `Model.exists(filter)` query helper

- src/__tests__/schema.test.ts
- src/__tests__/types.test.ts
- src/types.ts
When adding a test case in #312 I noticed that while we're correctly typing the output of required `oneOf` types, it doesn't match the underlying JSON schema implementation.
Currently the resulting property is always optional at the schema level - by adding the `$required: true` to the return object from the `oneOf` type function we ensure that the property is included in the `required` properties array and is validated appropriately by mongo on insert.
BREAKING CHANGE: This changes the produced JSON schema for required `oneOf` types to correctly include it in the resulting `required` properties array.
> fix: Correct `oneOf` required option

- docs/api/types.md
- src/__tests__/schema.test.ts
- src/__tests__/types.test.ts
- src/types.ts
This is useful for creating discriminated unions with the `oneOf` type.
Because we're forced to use JSON Schema draft 4 we don't have access to the `const` property, but we _do_ have access to `enum`, and `const` is [just syntactic sugar for a single-element `enum` anyway](https://json-schema.org/draft-06/json-schema-release-notes.html#:~:text=more%20readible%20form%20of%20a%20one%2Delement%20%22enum%22).
> feat: Support `constant` type

- docs/api/types.md
- src/__tests__/schema.test.ts
- src/__tests__/types.test.ts
- src/types.ts
While storing `null` literals in Mongo has some surprising semantics (and this author thinks the practice should be strongly discouraged), if you are trying to add a schema to a collection that already has literal `null` values stored we should make it possible to type that correctly.
I've added the raw `types.null()`, but have left it a bit intentionally difficult to use: naively using it results in a column that may _only_ contain the `null` value, so it should typically be combined with other types. I considered adding a helper like `types.nullable(types.number())` but I felt that adding that syntactic sugar would make folks more likely to use it.
> feat: `null` type

- .github/workflows/ci.yaml
We should be testing the `build` step in multiple node.js versions, since this is a library and we can't control where it's going to be used.
> test: Build in multiple node versions in CI

- src/utils.ts
`getIds` performs no transformation on incoming parameters.
By accepting `readonly` arrays of strings it is able to handle a wider variety of inputs.
By continuing to return a mutable array of ObjectIds, no existing consumers should be affected.
> feat: Util getIds accepts readonly structures

- CODE_OF_CONDUCT.md
- README.md
To attract more open source contributors we should establish some basic guidelines of working together.
I've used the Code of Conduct document found at https://www.contributor-covenant.org/, which seems to be widely used by a number of big open source projects.
> docs: Add Code of Conduct

- tests/cjs/package.json
- tests/esm/package.json
The build tests have started failing because the `mongodb` dependency in the build test `package.json` files were still using version `4.0.0`, even though our package requires `>=4.11.0`. This must be a new behavior in the `npm` client used to install that.
> test: Fix CI dependency

- src/__tests__/mongodbTypes.test.ts
- src/utils.ts
This PR adds support for type checking nested fields in a generic object (e.g. `Record<string, object>`).
Given a schema containing this field:
```ts
foo: Types.objectGeneric(Types.object({
title: Types.string()
}, { required: true }));
```
We can now write type checked filters:
```ts
await Test.find({ 'foo.any-key.title': 'Test title' });
```
> feat: Type check nested objects in generic objects

- src/__tests__/mongodbTypes.test.ts
- src/mongodbTypes.ts
- src/utils.ts
> **Note**
> BREAKING CHANGE: Nested properties after 6 levels of nesting are no longer type checked.
Ever since we added all the missing type checks in the update filters in v11, we've seen a degradation in TS check times in our private repository. A bit of overhead was to be expected from adding all those new type checks. However, the performance degradation we've experienced was too high.
We have a few complex models with deeply nested structures in our private repository, so we were seeing around a 1.2x increase in the TypeScript check time.
With the changes in this PR, we reduced the TS check time about 45% compared to v11.1.0. We're now experiencing only a 0.18x increase in the TS check time compared to v10.0.0.
> perf: Improve update filter types check times

- docs/api/model.md
- src/__tests__/model.test.ts
- src/model.ts
As @ejmartin504 discussed in #272 - rather than throwing when an empty array is passed to `model.bulkWrite` we can perform a no-op and exit early. 
BREAKING CHANGE: Changes the return type of `model.bulkWrite` to include `void`
Closes #272
> refactor: Perform no-op on `bulkWrite` when no operations provided

- docs/api/model.md
- src/__tests__/model.test.ts
- src/model.ts
This returns the mongodb `FindCursor` allowing users to handle iteration however they please in their applications without loading all results into memory at once.
This is an alternative to #453. In my opinion this implementation is better suited to the idea of Papr being a thin wrapper around the MongoDB driver.
> feat: Add `findCursor` model method

- .github/workflows/ci.yaml
- .vscode/settings.json
- docs/getting-started.md
- package.json
- yarn.lock
BREAKING CHANGE: Node.js v14 is not supported.
This old node.js version is currently in "Maintenance" mode. Let's remove support in the next release.
> refactor: Remove node.js v14 support

- docs/api/schema.md
- docs/recipes.md
- src/__tests__/model.test.ts
- src/__tests__/utils.test.ts
- src/model.ts
- src/schema.ts
- src/utils.ts
This introduces the ability for users to provide a function that returns default values rather than an object with static values. This is useful when you're using an `_id` value other than ObjectId and would like to keep the functionality of automatically generating an `_id` value on insert.
We continue with the existing behavior of only applying the default value for a path when the path is not included in the insert. This isn't technically a breaking change since all schemas will continue to work as expected.
Closes: plexinc/papr#18
> feat: Support dynamic default values

- package.json
- pnpm-lock.yaml
- src/__tests__/model.test.ts
- src/__tests__/mongodbTypes.test.ts
- src/model.ts
- tests/cjs/package.json
- tests/esm/package.json
- tests/ts-nodenext/package.json
- tests/ts/package.json
https://github.com/mongodb/node-mongodb-native/releases/tag/v6.0.0
BREAKING CHANGE: `mongodb` minimum version is now v6.*
BREAKING CHANGE: `node` minimum version is now v16.20.1
> feat: Upgrade mongodb to v6.0.0

- docs/api/model.md
- src/model.ts
Small typo fix in the documentation.
https://plexinc.github.io/papr/#/api/model?id=bulkwrite
> docs: Typo in bulkWrite description

- .github/workflows/ci.yaml
- package.json
- pnpm-lock.yaml
Node.js v20 has recently entered the LTS phase.
> chore: Upgrade node.js to v20.9.0

- docs/api/model.md
- src/__tests__/model.test.ts
- src/model.ts
Since `upsert` is just a wrapper around `findOneAndUpdate` we can allow users to pass options into the method. This also affords us the ability to remove an `as unknown` cast, instead relying on the returned type from mongo.
Closes: #707
> feat: Support options for upsert model method

- src/__tests__/types.test.ts
- src/types.ts
Fixes the return type of `types.oneOf`.
Closes: #715
> fix: Don't exclude null from oneOf return type

- src/__tests__/index.test.ts
- src/__tests__/model.test.ts
- src/__tests__/schema.test.ts
- src/index.ts
- src/schema.ts
We have a problem using import-in-the-middle (lib embedded inside opentelemetry), because this lib intercept and register a hook of modules. I found a issue that reexport of schema module, beceuse this module is export twice on index.js. 
The exception generated using import-in-the-middle, papr, and node20:
```
file:///Users/papr/esm/index.js?iitm=true:90
let $schema = $1707251817792598e86e3.schema
^
SyntaxError: Identifier '$schema' has already been declared
at ModuleLoader.moduleStrategy (node:internal/modules/esm/translators:167:18)
at callTranslator (node:internal/modules/esm/loader:285:14)
at ModuleLoader.moduleProvider (node:internal/modules/esm/loader:291:30)
Node.js v20.11.0
```
Thanks in advanced.
> fix: Export schema only once

- .github/workflows/plex.yaml
Related to #722, but without using a secret, which does not work for workflows running on PRs.
> test: Use Plex webhook URL

- src/__tests__/model.test.ts
- src/model.ts
- src/mongodbTypes.ts
Closes #830
As part of an attempt to improve papr's support for immutable data structures, this simple PR allows passing a readonly array of operations to the `bulkWrite` method.
> feat: bulkWrite method accepts readonly operations

- docs/schema.md
Fixes a mistake in the docs. :)
> docs: Use `type` instead of `const` in schema docs
